version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: masterlist-web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-secret-key
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
      - /app/__pycache__
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3